### ISSUE TITLE
Processing custom sqlite file

### ISSUE THREAD

**Issue by choudharya3** [neuml/paperai#10]
I want to create an index and vector file over a Custom sqlite articles database. I have created a articles.sqlite database on medical papers, using paperetl. But I did not find any instruction as to how to process it . Can you please give instructions on this ?

**Comment by davidmezzetti** [comment]
Here are the steps:

```bash
# Create vector file, currently builds vector file in ~/.cord19
python -m paperai.vectors <path to directory containing articles.sqlite>

# Index the data
python -m paperai.index <path to directory containing articles.sqlite>
```

I created issue #11 to add additional command line parameters to control the vector model creation process but right now the output file path is hardcoded

**Comment by choudharya3** [comment]
Hi David, 
Thank you very much for prompt response.

1) Vector file : It worked. I was actually passing the full path of the .sqlite file ( including the filename 'articles.sqlite' ). So, it was not working. It worked now, I see 'vectors' folder created in the path ~/.cord19

2) On the Index making step : A folder 'models' is not automatically created on the path ~/.cord19 . Instead 4 relevant files were created there.  I  created a folder 'models' and then put these 4 files inside the folder. Then it worked.

Thanks very much for your help.

**Comment by davidmezzetti** [comment]
Marking issue as resolved
