### ISSUE TITLE
How to use it with specific scientific papers?

### ISSUE THREAD

**Issue by VolkovIlia** [neuml/paperai#53]
I working in the field of material science. Can you give some instructions how to use it with PDF papers?

**Comment by davidmezzetti** [comment]
Thank you for giving paperai a try.

The first thing you need to do is load PDFs into a database with paperetl - https://github.com/neuml/paperetl#load-pdf-articles-into-sqlite

Once you have that, you would then be able to build paperai models/indexes - https://github.com/neuml/paperai#building-a-model

The upcoming release of both paperetl and paperai will put effort towards updating the documentation.

**Comment by HyderPang** [comment]
Thanks for your efforts. Hope you guys focus on the improvement on universality and simplicity of paperai in the future, as researchers out of NLP domain eagering to utilize this promising tool to improve their research.
