### ISSUE TITLE
sqlite3.OperationalError: no such table: sections

### ISSUE THREAD

**Issue by wspspring** [neuml/paperai#55]
when I command in a docker: python -m paperai.vectors cord19/models, the output srror is "sqlite3.OperationalError: no such table: sections"

**Comment by davidmezzetti** [comment]
This sounds like an issue where the cord19/models directory is empty. What happens if you run `ls -l cord19/models/articles.sqlite`. 

Did you use [paperetl](https://github.com/neuml/paperetl) to build an index? If so, cord19/models should be replaced with the output path from paperetl.
