### ISSUE TITLE
Error in models.py file of paperai pip package

### ISSUE THREAD

**Issue by SoenkevL** [neuml/paperai#77]
When I installed Paperai using pip version 24.0 for python3.11 I got an error that my Embedding was of type None. I could locate the error. There is an issue in the model.py file in line 31 where it should be "if os.path.isfile(os.path.join(path, "config.json")):" instead of "if os.path.isfile(os.path.join(path, "config")):". Atleast that resolved the error for me and afterwards the program worked fine again.

**Comment by Spiffical** [comment]
Thanks for addressing this! Easy fix.
